[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-Lnative=/opt/xwin/crt/lib/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/um/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/ucrt/x86_64",
]

[target.aarch64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-Lnative=/opt/xwin-arm64/crt/lib/aarch64",
  "-Lnative=/opt/xwin-arm64/sdk/lib/um/aarch64",
  "-Lnative=/opt/xwin-arm64/sdk/lib/ucrt/aarch64",
]

[env]
XWIN_ARCH = "x86_64"
